[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Server = "Atari 2600"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self'; connect-src *; font-src fonts.gstatic.com; manifest-src 'self'; worker-src 'self';"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Feature-Policy = "payment 'self'; geolocation 'self';"